### ISSUE TITLE
don't require task functions to be generators

### ISSUE THREAD

**Issue by dherman** [mozilla/task.js#16]
There's absolutely no reason a task function should have to be a generator function. As long as it produces an iterator object, that's all we should care about. I.e., it should be duck typed.

**Comment by dherman** [comment]
https://github.com/dherman/taskjs/commit/f9700fa0872e4323bc98f1b5d6b76c007e90bd2c

**Comment by jkroso** [comment]
What happened with this, is task.js supporting iterators now? the link to the commit is broken
