### ISSUE TITLE
lib/task.dom.js missing

### ISSUE THREAD

**Issue by rwaldron** [mozilla/task.js#21]
In `examples/finish.html` there is a script referenced at `lib/task.dom.js` which is missing from the repo. I ran the example in Firefox and it was only able to output the following:

```
outer task waiting...
inner task working...
inner task finishing...
```

...However it doesn't seem like anything in the example code is depending on anything other then task.js

**Comment by dherman** [comment]
Fixed in

```
https://github.com/mozilla/task.js/commit/19788e737a18bd14e23b6f188846ab99d7d2f7b8
```

Thanks,
Dave

**Comment by rwaldron** [comment]
Excellent, thanks!
