### ISSUE TITLE
are there any ideas to make an abstraction on top of task.js?

### ISSUE THREAD

**Issue by opensourcegeek** [mozilla/task.js#37]
One of the libraries I recently played with for doing non-blocking I/O is called gevent from python community. The nice thing was you can have a completely readable synchronous code yet the run time was non-blocking and managed cooperative scheduling. The gevent library monkey patched some of the system API level calls like "opening a socket" for example. I was wondering if there is a place for an abstraction like that on top of task.js so that there is no yield statements in users code.

**Comment by lm1** [comment]
It is not possible to avoid yield at caller site without source translation. Using generators similarly to await requires explicit propagation throughout the call chain. This is a language design choice. The downside is that it's not as composable as coroutines but the advantage is that it is always clear where the control is given away so maintaining consistency of the program global state is more manageable.
You may want to play with Rihno JavaScript engine which implements [continuations](http://wiki.apache.org/cocoon/RhinoWithContinuations) and therefore make implicit yield possible.

**Comment by opensourcegeek** [comment]
I thought it would be very useful to have that alternate approach especially on server side javascript. Ah, well - good to know. Thanks.
