### ISSUE TITLE
Publish the library on bower or npm

### ISSUE THREAD

**Issue by andresoct** [mozilla/task.js#39]
Hi,
I think this library should be published on bower or npm, I can help adding a task runner (gulp or grunt), minify the code and ship it to bower and / or npm.
Let me know if this is something you want to accomplish.
Regards

**Comment by migsc** [comment]
+1. Working on a project using the RSVP promise library in nodejs, and I'd like to work with task.js as it is [the recommended way](https://github.com/tildeio/rsvp.js#taskjs) to create synchronous promise-oriented code with RSVP. I've created my own local private npm package in the meantime as a workaround.

**Comment by acjay** [comment]
+1.

Is there a comparable library already on NPM?

**Comment by andresoct** [comment]
I tried to contact the main contributor @dherman , but not response so far, so I'll wait on confirmation to start with this feature
